package objects

// COTSymbol ...
type COTSymbol struct {
	TradingSymbol string `json:"trading_symbol"`
	ShortName     string `json:"short_name"`
}

// COTReport ...
type COTReport struct {
	Symbol                      string  `json:"symbol"`
	Date                        string  `json:"date"`
	ShortName                   string  `json:"short_name"`
	Sector                      string  `json:"sector"`
	MarketAndExchangeNames      string  `json:"market_and_exchange_names"`
	AsOfDateInFormYymmdd        string  `json:"as_of_date_in_form_yymmdd"`
	CftcContractMarketCode      string  `json:"cftc_contract_market_code"`
	CftcMarketCode              string  `json:"cftc_market_code"`
	CftcRegionCode              string  `json:"cftc_region_code"`
	CftcCommodityCode           string  `json:"cftc_commodity_code"`
	ContractUnits               string  `json:"contract_units"`
	OpenInterestAll             float64 `json:"open_interest_all"`
	NoncommPositionsLongAll     float64 `json:"noncomm_positions_long_all"`
	NoncommPositionsShortAll    float64 `json:"noncomm_positions_short_all"`
	NoncommPostionsSpreadAll    float64 `json:"noncomm_postions_spread_all"`
	CommPositionsLongAll        float64 `json:"comm_positions_long_all"`
	CommPositionsShortAll       float64 `json:"comm_positions_short_all"`
	TotReptPositionsLongAll     float64 `json:"tot_rept_positions_long_all"`
	TotReptPositionsShortAll    float64 `json:"tot_rept_positions_short_all"`
	NonreptPositionsLongAll     float64 `json:"nonrept_positions_long_all"`
	NonreptPositionsShortAll    float64 `json:"nonrept_positions_short_all"`
	OpenInterestOld             float64 `json:"open_interest_old"`
	NoncommPositionsLongOld     float64 `json:"noncomm_positions_long_old"`
	NoncommPositionsShortOld    float64 `json:"noncomm_positions_short_old"`
	NoncommPositionsSpreadOld   float64 `json:"noncomm_positions_spread_old"`
	CommPositionsLongOld        float64 `json:"comm_positions_long_old"`
	CommPositionsShortOld       float64 `json:"comm_positions_short_old"`
	TotReptPositionsLongOld     float64 `json:"tot_rept_positions_long_old"`
	TotReptPositionsShortOld    float64 `json:"tot_rept_positions_short_old"`
	NonreptPositionsLongOld     float64 `json:"nonrept_positions_long_old"`
	NonreptPositionsShortOld    float64 `json:"nonrept_positions_short_old"`
	OpenInterestOther           float64 `json:"open_interest_other"`
	NoncommPositionsLongOther   float64 `json:"noncomm_positions_long_other"`
	NoncommPositionsShortOther  float64 `json:"noncomm_positions_short_other"`
	NoncommPositionsSpreadOther float64 `json:"noncomm_positions_spread_other"`
	CommPositionsLongOther      float64 `json:"comm_positions_long_other"`
	CommPositionsShortOther     float64 `json:"comm_positions_short_other"`
	TotReptPositionsLongOther   float64 `json:"tot_rept_positions_long_other"`
	TotReptPositionsShortOther  float64 `json:"tot_rept_positions_short_other"`
	NonreptPositionsLongOther   float64 `json:"nonrept_positions_long_other"`
	NonreptPositionsShortOther  float64 `json:"nonrept_positions_short_other"`
	ChangeInOpenInterestAll     float64 `json:"change_in_open_interest_all"`
	ChangeInNoncommLongAll      float64 `json:"change_in_noncomm_long_all"`
	ChangeInNoncommShortAll     float64 `json:"change_in_noncomm_short_all"`
	ChangeInNoncommSpeadAll     float64 `json:"change_in_noncomm_spead_all"`
	ChangeInCommLongAll         float64 `json:"change_in_comm_long_all"`
	ChangeInCommShortAll        float64 `json:"change_in_comm_short_all"`
	ChangeInTotReptLongAll      float64 `json:"change_in_tot_rept_long_all"`
	ChangeInTotReptShortAll     float64 `json:"change_in_tot_rept_short_all"`
	ChangeInNonreptLongAll      float64 `json:"change_in_nonrept_long_all"`
	ChangeInNonreptShortAll     float64 `json:"change_in_nonrept_short_all"`
	PctOfOpenInterestAll        float64 `json:"pct_of_open_interest_all"`
	PctOfOiNoncommLongAll       float64 `json:"pct_of_oi_noncomm_long_all"`
	PctOfOiNoncommShortAll      float64 `json:"pct_of_oi_noncomm_short_all"`
	PctOfOiNoncommSpreadAll     float64 `json:"pct_of_oi_noncomm_spread_all"`
	PctOfOiCommLongAll          float64 `json:"pct_of_oi_comm_long_all"`
	PctOfOiCommShortAll         float64 `json:"pct_of_oi_comm_short_all"`
	PctOfOiTotReptLongAll       float64 `json:"pct_of_oi_tot_rept_long_all"`
	PctOfOiTotReptShortAll      float64 `json:"pct_of_oi_tot_rept_short_all"`
	PctOfOiNonreptLongAll       float64 `json:"pct_of_oi_nonrept_long_all"`
	PctOfOiNonreptShortAll      float64 `json:"pct_of_oi_nonrept_short_all"`
	PctOfOpenInterestOl         float64 `json:"pct_of_open_interest_ol"`
	PctOfOiNoncommLongOl        float64 `json:"pct_of_oi_noncomm_long_ol"`
	PctOfOiNoncommShortOl       float64 `json:"pct_of_oi_noncomm_short_ol"`
	PctOfOiNoncommSpreadOl      float64 `json:"pct_of_oi_noncomm_spread_ol"`
	PctOfOiCommLongOl           float64 `json:"pct_of_oi_comm_long_ol"`
	PctOfOiCommShortOl          float64 `json:"pct_of_oi_comm_short_ol"`
	PctOfOiTotReptLongOl        float64 `json:"pct_of_oi_tot_rept_long_ol"`
	PctOfOiTotReptShortOl       float64 `json:"pct_of_oi_tot_rept_short_ol"`
	PctOfOiNonreptLongOl        float64 `json:"pct_of_oi_nonrept_long_ol"`
	PctOfOiNonreptShortOl       float64 `json:"pct_of_oi_nonrept_short_ol"`
	PctOfOpenInterestOther      float64 `json:"pct_of_open_interest_other"`
	PctOfOiNoncommLongOther     float64 `json:"pct_of_oi_noncomm_long_other"`
	PctOfOiNoncommShortOther    float64 `json:"pct_of_oi_noncomm_short_other"`
	PctOfOiNoncommSpreadOther   float64 `json:"pct_of_oi_noncomm_spread_other"`
	PctOfOiCommLongOther        float64 `json:"pct_of_oi_comm_long_other"`
	PctOfOiCommShortOther       float64 `json:"pct_of_oi_comm_short_other"`
	PctOfOiTotReptLongOther     float64 `json:"pct_of_oi_tot_rept_long_other"`
	PctOfOiTotReptShortOther    float64 `json:"pct_of_oi_tot_rept_short_other"`
	PctOfOiNonreptLongOther     float64 `json:"pct_of_oi_nonrept_long_other"`
	PctOfOiNonreptShortOther    float64 `json:"pct_of_oi_nonrept_short_other"`
	TradersTotAll               float64 `json:"traders_tot_all"`
	TradersNoncommLongAll       float64 `json:"traders_noncomm_long_all"`
	TradersNoncommShortAll      float64 `json:"traders_noncomm_short_all"`
	TradersNoncommSpreadAll     float64 `json:"traders_noncomm_spread_all"`
	TradersCommLongAll          float64 `json:"traders_comm_long_all"`
	TradersCommShortAll         float64 `json:"traders_comm_short_all"`
	TradersTotReptLongAll       float64 `json:"traders_tot_rept_long_all"`
	TradersTotReptShortAll      float64 `json:"traders_tot_rept_short_all"`
	TradersTotOl                float64 `json:"traders_tot_ol"`
	TradersNoncommLongOl        float64 `json:"traders_noncomm_long_ol"`
	TradersNoncommShortOl       float64 `json:"traders_noncomm_short_ol"`
	TradersNoncommSpeadOl       float64 `json:"traders_noncomm_spead_ol"`
	TradersCommLongOl           float64 `json:"traders_comm_long_ol"`
	TradersCommShortOl          float64 `json:"traders_comm_short_ol"`
	TradersTotReptLongOl        float64 `json:"traders_tot_rept_long_ol"`
	TradersTotReptShortOl       float64 `json:"traders_tot_rept_short_ol"`
	TradersTotOther             float64 `json:"traders_tot_other"`
	TradersNoncommLongOther     float64 `json:"traders_noncomm_long_other"`
	TradersNoncommShortOther    float64 `json:"traders_noncomm_short_other"`
	TradersNoncommSpreadOther   float64 `json:"traders_noncomm_spread_other"`
	TradersCommLongOther        float64 `json:"traders_comm_long_other"`
	TradersCommShortOther       float64 `json:"traders_comm_short_other"`
	TradersTotReptLongOther     float64 `json:"traders_tot_rept_long_other"`
	TradersTotReptShortOther    float64 `json:"traders_tot_rept_short_other"`
	ConcGrossLe4TdrLongAll      float64 `json:"conc_gross_le_4_tdr_long_all"`
	ConcGrossLe4TdrShortAll     float64 `json:"conc_gross_le_4_tdr_short_all"`
	ConcGrossLe8TdrLongAll      float64 `json:"conc_gross_le_8_tdr_long_all"`
	ConcGrossLe8TdrShortAll     float64 `json:"conc_gross_le_8_tdr_short_all"`
	ConcNetLe4TdrLongAll        float64 `json:"conc_net_le_4_tdr_long_all"`
	ConcNetLe4TdrShortAll       float64 `json:"conc_net_le_4_tdr_short_all"`
	ConcNetLe8TdrLongAll        float64 `json:"conc_net_le_8_tdr_long_all"`
	ConcNetLe8TdrShortAll       float64 `json:"conc_net_le_8_tdr_short_all"`
	ConcGrossLe4TdrLongOl       float64 `json:"conc_gross_le_4_tdr_long_ol"`
	ConcGrossLe4TdrShortOl      float64 `json:"conc_gross_le_4_tdr_short_ol"`
	ConcGrossLe8TdrLongOl       float64 `json:"conc_gross_le_8_tdr_long_ol"`
	ConcGrossLe8TdrShortOl      float64 `json:"conc_gross_le_8_tdr_short_ol"`
	ConcNetLe4TdrLongOl         float64 `json:"conc_net_le_4_tdr_long_ol"`
	ConcNetLe4TdrShortOl        float64 `json:"conc_net_le_4_tdr_short_ol"`
	ConcNetLe8TdrLongOl         float64 `json:"conc_net_le_8_tdr_long_ol"`
	ConcNetLe8TdrShortOl        float64 `json:"conc_net_le_8_tdr_short_ol"`
	ConcGrossLe4TdrLongOther    float64 `json:"conc_gross_le_4_tdr_long_other"`
	ConcGrossLe4TdrShortOther   float64 `json:"conc_gross_le_4_tdr_short_other"`
	ConcGrossLe8TdrLongOther    float64 `json:"conc_gross_le_8_tdr_long_other"`
	ConcGrossLe8TdrShortOther   float64 `json:"conc_gross_le_8_tdr_short_other"`
	ConcNetLe4TdrLongOther      float64 `json:"conc_net_le_4_tdr_long_other"`
	ConcNetLe4TdrShortOther     float64 `json:"conc_net_le_4_tdr_short_other"`
	ConcNetLe8TdrLongOther      float64 `json:"conc_net_le_8_tdr_long_other"`
	ConcNetLe8TdrShortOther     float64 `json:"conc_net_le_8_tdr_short_other"`
}

// COTAnalysis ...
type COTAnalysis struct {
	Symbol                       string  `json:"symbol"`
	Date                         string  `json:"date"`
	Name                         string  `json:"name"`
	Sector                       string  `json:"sector"`
	Exchange                     string  `json:"exchange"`
	MarketSituation              string  `json:"marketSituation"`
	MarketSentiment              string  `json:"marketSentiment"`
	PreviousMarketSituation      string  `json:"previousMarketSituation"`
	CurrentlongmarketSituation   float64 `json:"currentLongMarketSituation"`
	CurrentShortMarketSituation  float64 `json:"currentShortMarketSituation"`
	PreviousLongMarketSituation  float64 `json:"previousLongMarketSituation"`
	PreviousShortMarketSituation float64 `json:"previousShortMarketSituation"`
	NetPostion                   float64 `json:"netPostion"`
	PreviousNetPosition          float64 `json:"previousNetPosition"`
	ChangeInNetPosition          float64 `json:"changeInNetPosition"`
	ReversalTrend                bool    `json:"reversalTrend"`
}
